Move OTel constants under span-normalizer-constants
hypertrace/hypertrace-ingester pull request #77
Opened 2020-11-28 08:03 UTC by rish691

2020-11-28 09:12 UTC, kotharironak approved these changes

2020-11-28 09:43 UTC, kotharironak requested changes
I am not sure of the usage of these constants eventually. So, if we can localize, it should be fine instead of publishing.

2020-11-28 21:14 UTC, rish691 commented
> I am not sure of the usage of these constants eventually. So, if we can localize, it should be fine instead of publishing.

Until we have a clear plan on removing the usage of the constants from the platform, I think we should expose it. 
Also consider that if module from this repository has to be consumed as artifact instead of sub-module, we will have to then expose the constants.

2020-11-30 07:14 UTC, kotharironak approved these changes
As discussed, approving this.

2020-11-30 07:24 UTC, merged